# Заголовок

In [1]:
import math

In [2]:
print(math.comb(12, 3))

220


In [3]:
math.comb(12, 5)

792

In [4]:
math.factorial(5)

120

In [5]:
import math as m

In [6]:
m.gcd(120, 210, 360)

30

In [7]:
m.lcm(10, 20, 30, 40)

120

In [8]:
import numpy as np

In [9]:
a = np.arange(1, 13).reshape(4, 3)
print(a)
print('Transpose')
print(a.transpose())
print('Turn left')
print(np.rot90(a))
print('Turn right')
print(np.rot90(a, -1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Transpose
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Turn left
[[ 3  6  9 12]
 [ 2  5  8 11]
 [ 1  4  7 10]]
Turn right
[[10  7  4  1]
 [11  8  5  2]
 [12  9  6  3]]


In [10]:
print(a.mT)
print(a.T)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [11]:
import numpy as np
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.min(axis=0))
print(a.max(axis=1))

[12 15 18]
[ 6 15 24]
[1 2 3]
[3 6 9]


In [12]:
a = np.arange(1,16).reshape(3,5)
print(a)
print(a[:2,3:])
print()
print(a[::2,::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 4  5]
 [ 9 10]]

[[ 1  3  5]
 [11 13 15]]


In [13]:
import pandas as pd

In [15]:
d = { "a": 10, "b": 20, "c": 30, "d": 40, "e": 50 }
print(pd.Series(d))
print()
print(pd.Series(d, index=["a", "b", "c", "d"]))
print()
d = { "a": 10, "b": 20, "c": 30, "e": 50 }
print(pd.Series(d, index=["a", "b", "c", "d"]))

a    10
b    20
c    30
d    40
e    50
dtype: int64

a    10
b    20
c    30
d    40
dtype: int64

a    10.0
b    20.0
c    30.0
d     NaN
dtype: float64


In [26]:
students = pd.read_csv("Students_Performance.csv")
pd.DataFrame(students)

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  
0                      none          72             72             74  
1                 completed          69             90             88  
2                      none          90             95             93  
3                      none          47             57             44  
4                      none          76             78             75  
..                      ...         ...            ...            ...  
995               completed          88             99             95  
996                    none          62             55             55  
997               completed          59             71             65  
998               completed          68             78             77  
999                    none          77             86             86  

[1000 rows x 8 columns]

In [31]:
with_course = students[students["test preparation course"] == "completed"]
with_course

gender race/ethnicity parental level of education         lunch  \
1    female        group C                some college      standard   
6    female        group B                some college      standard   
8      male        group D                 high school  free/reduced   
13     male        group A                some college      standard   
18     male        group C             master's degree  free/reduced   
..      ...            ...                         ...           ...   
990    male        group E                 high school  free/reduced   
991  female        group B            some high school      standard   
995  female        group E             master's degree      standard   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   

    test preparation course  math score  reading score  writing score  
1                 completed          69             90             88  
6                 completed          88             95             92  
8                 completed          64             64             67  
13                completed          78             72             70  
18                completed          46             42             46  
..                      ...         ...            ...            ...  
990               completed          86             81             75  
991               completed          65             82             78  
995               completed          88             99             95  
997               completed          59             71             65  
998               completed          68             78             77  

[358 rows x 8 columns]

In [36]:
with_course[["math score", "reading score", "writing score"]].sort_values(["math score", "reading score", "writing score"], ascending=False)

math score  reading score  writing score
916         100            100            100
149         100            100             93
625         100             97             99
623         100             96             86
114          99            100            100
..          ...            ...            ...
339          35             55             60
902          34             48             41
785          32             51             44
683          29             40             44
842          23             44             36

[358 rows x 3 columns]

In [40]:
students["total score"] = students["math score"] + students["reading score"] + students["writing score"]
students.sort_values("total score", ascending=False).head(15)

gender race/ethnicity parental level of education         lunch  \
916    male        group E           bachelor's degree      standard   
962  female        group E          associate's degree      standard   
458  female        group E           bachelor's degree      standard   
114  female        group E           bachelor's degree      standard   
712  female        group D                some college      standard   
179  female        group D            some high school      standard   
165  female        group C           bachelor's degree      standard   
625    male        group D                some college      standard   
685  female        group E             master's degree      standard   
903  female        group D           bachelor's degree  free/reduced   
149    male        group E          associate's degree  free/reduced   
957  female        group D             master's degree      standard   
566  female        group E           bachelor's degree  free/reduced   
594  female        group C           bachelor's degree      standard   
717  female        group C          associate's degree      standard   

    test preparation course  math score  reading score  writing score  \
916               completed         100            100            100   
962                    none         100            100            100   
458                    none         100            100            100   
114               completed          99            100            100   
712                    none          98            100             99   
179               completed          97            100            100   
165               completed          96            100            100   
625               completed         100             97             99   
685               completed          94             99            100   
903               completed          93            100            100   
149               completed         100            100             93   
957                    none          92            100            100   
566               completed          92            100            100   
594               completed          92            100             99   
717               completed          96             96             99   

     total score  
916          300  
962          300  
458          300  
114          299  
712          297  
179          297  
165          296  
625          296  
685          293  
903          293  
149          293  
957          292  
566          292  
594          291  
717          291

In [43]:
students.groupby(["gender","test preparation course"])["writing score"].count()

gender  test preparation course
female  completed                  184
        none                       334
male    completed                  174
        none                       308
Name: writing score, dtype: int64

In [45]:
agg_functions = {"math score":["mean", "median"]}
students.groupby(["gender","test preparation course"]).agg(agg_functions)

math score       
                                     mean median
gender test preparation course                  
female completed                67.195652   67.0
       none                     61.670659   62.0
male   completed                72.339080   73.0
       none                     66.688312   67.0

# 14.05.2025